### ISSUE TITLE
メイン画像の作成

### ISSUE THREAD

**Issue by misha-endo** [wct2016/wct2016#1]
3/1の情報公開時点のメインビジュアル画像を作成する

**Comment by featherplain** [comment]
↑ごめんなさい、誤操作です!!!1

**Comment by featherplain** [comment]
@misha-endo 
- 期限を教えて下さい。
- 画像のサイズを教えて下さい!
- 作った画像は google Drive にアップロードで OK ?
- 作業完了後の Assignee の記載をお願いします!

**Comment by osugi0107** [comment]
@featherplain 
昨年度のワプーの「？」シルエットaiデータの所在とかってご存知でしょうか？
もしデータがあればいただきたいです！

**Comment by featherplain** [comment]
@osugi0107 

Gドライブにアップしました!
`2015/design/silhouette` を見てください。

フォントは Gotham を使っているのですが、そのままでもいいですし、好きなフォントに変えちゃってください!

**Comment by misha-endo** [comment]
期限は2/26（金）
画像サイズ :1200x400~600くらい
（場合によりリサイズをお願いするかもです）

作った画像は google Drive にアップロード OK です
作業完了後の Assignee は遠藤でお願い致します

**Comment by osugi0107** [comment]
@featherplain ありがとうございます！了解しましたー！

**Comment by osugi0107** [comment]
@misha-endo 
このような形となりましたが、いかがでしょうか？皆様もご意見あれば、ぜひ。
Googleドライブに元データあります。

・前回とほぼ同じじゃないか！と言われると泣いちゃいます
　テーマが「夜明け」なので、そこからはブレていないのではと思います
・少しグラデーションで朝焼け感を出しました
・話題に出てた「？」ワプーも配置しました

![wct2016-is-announced](https://cloud.githubusercontent.com/assets/2011164/13340279/7da3cac4-dc72-11e5-9d35-cb49b603854d.png)

**Comment by osugi0107** [comment]
@misha-endo 
よくよく考えるとサイズが指定のもの違っていますね…。
すいません。デザインFIX後、リサイズします。

**Comment by misha-endo** [comment]
@osugi0107 ありがとうございます！大丈夫です。ありがとうございます！確認をとりますね〜

**Comment by misha-endo** [comment]
@osugi0107 リサイズも決まり次第で大丈夫です〜

**Comment by misha-endo** [comment]
夜明けってかんじですね〜〜〜
今年のテーマは省力化ですし、去年と似ていて全然問題ないです

**Comment by misha-endo** [comment]
@osugi0107 
高野さんから、連絡がありました。

> ありがとうございます。ステキですー！今日いっぱいくらい意見を待って、問題なければ明日全体グループでも共有してください。

とのことです。
ありがとうございます〜〜

**Comment by osugi0107** [comment]
@misha-endo 
了解です！引き続き、よろしくお願いします！

**Comment by misha-endo** [comment]
@osugi0107 
委員長より下記ご意見をいただきました。

お手数ですが、高さのご調整をおねがいしてもよろしいでしょうか？

イメージ画像が13インチラップトップ画面だとかなり大きいなぁと感じました。画像の余白的な部分をなるべくタイトにして、もう少し高さを縮めたほうがいいのかな

**Comment by osugi0107** [comment]
@misha-endo 
確かに大きいですね。こちらですが、<header>タグのpaddingも少し大きいかと思うのですが、調整って可能なのでしょうか？それによって、メイン画像の高さも変わってくるかと思いますね。

**Comment by misha-endo** [comment]
@osugi0107 返信がおそくなってすいません。
cssは、編集できるのでpaddingは調整できます。
ただ、media queryで細かく設定されているので修正は少し大変そうです。

画像の高さを80％くらいにしていただけたら、大丈夫かなと思っていますが、いかがでしょうか？

**Comment by osugi0107** [comment]
@misha-endo 
了解です。ここにあまり時間かけても仕方ないので、現在の80%程度のサイズにリサイズして対応としましょう！今日中に上げます！

**Comment by misha-endo** [comment]
@osugi0107 ありがとうございます。
よろしくお願い致します。

**Comment by osugi0107** [comment]
@misha-endo 
縮小版の画像を下記にアップしました。お手すきでご確認ください！
`2016_Main_visual/slice/wct2016-is-announced_teaser.png`

<img width="1271" alt="2016-03-08 22 33 56" src="https://cloud.githubusercontent.com/assets/2011164/13603132/5f9f2e5a-e57e-11e5-8a4d-0339509b7031.png">

**Comment by misha-endo** [comment]
@osugi0107 早々のご対応ありがとうございます。
設定してみました。
pcでは、いい感じだと思うのですが
個人的に、spくらいのサイズになった時に下wordcampの画像に負けてしまった感があり
せっかく、つくっていただいたのにすごく残念に感じます・・・

前の画像の8から7割縮小が負けないくらいでよいかなと思ったのですがいかがでしょうか・・・
あまり、お手数をおかけするような場所でないのですが・・・

![2016-03-08 11 09 04](https://cloud.githubusercontent.com/assets/12777029/13603892/b4de0148-e583-11e5-918a-909d14194f02.png)

**Comment by misha-endo** [comment]
@osugi0107 
jsとかがつかえれば、spのときはで使い分けれるかなと思ったのですがやっぱりテーマの編集ができないみたいで。。。

**Comment by featherplain** [comment]
@misha-endo 
横から失礼いたしますー
一番ラクな方法として、下の WordCamp の画像を使わない方法はだめでしょうか? w
メイン画像に比べて重要度低いし、4/11 の本公開でまた復活させればよいと思います。

**Comment by osugi0107** [comment]
@misha-endo 
スマホ、考慮していませんでしたねw あちらが立てば、こちらが立たず…
今リサイズ版を作って、上書きしました。
2016_Main_visual/slice/wct2016-is-announced_teaser.png

@featherplain さんのおっしゃるように、画像を消してしまっていいのなら、消してしまうのも手だとは思いますが…。ご判断おまかせします！

**Comment by misha-endo** [comment]
@osugi0107 ありがとうございます。
https://2016.tokyo.wordcamp.org/what-is-wordcamp/

いれました。いい感じかと思います〜。ありがとうございます。
![wct2016-is-announced_teaser 1](https://cloud.githubusercontent.com/assets/12777029/13625141/ce679a24-e5f7-11e5-88bc-4f87f0b99e1a.png)

@featherplain ご意見ありがとうございます。
消してもよいかとは思うのですが、
https://2016.tokyo.wordcamp.org/what-is-wordcamp/
このくらいであれば大丈夫かなと思うのですがいかがでしょうか？？

**Comment by featherplain** [comment]
@misha-endo @osugi0107 あ、いい感じですね!

**Comment by misha-endo** [comment]
@featherplain @osugi0107 ありがとうございます。
