### ISSUE TITLE
リサイズのバナー作成（WordCamp Central・facebookのカバー画像）

### ISSUE THREAD

**Issue by misha-endo** [wct2016/wct2016#11]
タイトルの2つの画像作成をお願い致します。

サイズや位置は下記リンク先を参照ください。

[ wordcamp2015のサイズ一覧 ]
スプレッドシートの画像シートを参照

[ facebook文字の位置 参考 ]
http://hapisupu.com/2015/09/facebook-cover-image-optimized/

**Comment by osugi0107** [comment]
@misha-endo 
了解しました。
ちなみにですが、こちらは自分が「#1 メイン画像の作成」で作成した画像のリサイズという認識であっていますでしょうか？
あと、その場合ワプーのシルエットは削除してしまってよろしいですか？

**Comment by misha-endo** [comment]
@osugi0107 よろしくお願い致します。

＞こちらは自分が「#1 メイン画像の作成」で作成した画像のリサイズという認識であっていますでしょうか？

あっています。

の場合ワプーのシルエットは削除いただいても大丈夫です。
※どちらでも、問題ありません。

**Comment by osugi0107** [comment]
@misha-endo 
了解です！遅くとも明日中完了予定で進めます。

**Comment by misha-endo** [comment]
@osugi0107 ありがとうございます。急にすいません。ありがとうございます。

**Comment by osugi0107** [comment]
@misha-endo 
対応完了しました。Googleドライブの下記にアップしました。
ご確認をよろしくお願い致します。
`2016_Main_visual/slice/`

**Comment by misha-endo** [comment]
@osugi0107 ご対応ありがとうございます！！

確認させていただきます！！

**Comment by misha-endo** [comment]
@osugi0107 みました！素敵です。
ありがとうございます〜〜

![寿司ゆき:happy](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/24.png)

**Comment by osugi0107** [comment]
@misha-endo 
よかったです！他にも何かあれば連絡ください！

issueの内容、完了判断になりましたら#1も含め、どんどんCloseしていただければと思います！

**Comment by misha-endo** [comment]
@osugi0107 
ありがとうございます！
了解いたしました。そうですね。closeさせていただきます。
