### ISSUE TITLE
タイムテーブルでのスピーカーページへのリンク

### ISSUE THREAD

**Issue by taroooo2o8** [wct2016/wct2016#110]

**Comment by taroooo2o8** [comment]
セッション詳細ページに行ってからのリンクしか出来ないそうです。

**Comment by featherplain** [comment]
@taroooo2o8 

タイムテーブルの各トラック内のスピーカーに対してリンクをはりたい、ということで合ってますか? (違っていたらすみません)

<img width="245" alt="capture" src="https://cloud.githubusercontent.com/assets/7019355/17759828/d92becfe-6535-11e6-8db2-2c71ddf334fb.png">

もしそうであれば、スピーカー一覧ページを作成して`[speakers]` のショートコードを設置して、公開するとスピーカー情報とタイムテーブルが紐付いて、タイムテーブル内の各トラックのスピーカー名がリンクになります。リンク先は、`speakers/#wcorg-speaker-{speaker_slug}` になります。

スピーカー一覧 : https://2016.tokyo.wordcamp.org/speakers/
タイムテーブル: https://2016.tokyo.wordcamp.org/schedule/

**Comment by taroooo2o8** [comment]
@featherplain 
そうです！そこです！
出来るんですね

**Comment by featherplain** [comment]
@taroooo2o8 はいー。できますよ! というわけでスピーカー一覧ページ勝手に公開しました。
