### ISSUE TITLE
タイムテーブルにカテゴリを追加したい

### ISSUE THREAD

**Issue by taroooo2o8** [wct2016/wct2016#112]
出来れば追加したい
これは当日まででも大丈夫かもしれない
去年みたいにアイコンでいいかも
https://2015.tokyo.wordcamp.org/schedule/

**Comment by taroooo2o8** [comment]
今回のタイムテーブルでは厳しいそうです。

**Comment by featherplain** [comment]
@taroooo2o8 

![image](https://cloud.githubusercontent.com/assets/7019355/17760097/fff44adc-6537-11e6-8414-187730101ec4.png)

こんな感じにしたいってことでしょうか? 去年みたいな「〇〇向け」のタグをつけるってことですよね。参考に今年の WCEurpe を載せました。-> https://2016.europe.wordcamp.org/schedule/

CSS で頑張ればできますが、もしやるとするならセッション情報が全て出揃ってから、限定的に「初心者向け」のみとかにしたいですね。対応の優先度としては低く設定するので、ホントに当日までに間に合わせる感じにはなるかも

**Comment by taroooo2o8** [comment]
@featherplain 
![2016-08-18 11 42 32](https://cloud.githubusercontent.com/assets/17106648/17760203/ef3e1eba-6538-11e6-91dd-84220dcda2ff.png)

これは去年のタイムテーブルなんですが
去年のようにしたら分かりやすいかもというのを斎木さんと話していました

**Comment by featherplain** [comment]
@taroooo2o8 
去年そのタイムテーブル作ったのは私でございますー:smile:

去年は、自力で HTML 組んでたので自由度も高い反面、 HTML が複雑になり更新作業がとても面倒だったのと、情報をいろいろ入れた結果ちょっとごちゃついてしまったなーという反省点があります。

今年はすべてショートコードで表示させるようにしているので、表示できるものは WordCamp サイトの機能(仕様)に左右される形になります。カテゴリ表示機能はない(多分)のでどうしても、という場合は CSS でどうにか頑張る感じです。

> CSS で頑張ればできますが、もしやるとするならセッション情報が全て出揃ってから、限定的に「初心者向け」のみとかにしたいですね。対応の優先度としては低く設定するので、ホントに当日までに間に合わせる感じにはなるかも

という方向でいきたいですー

**Comment by fumikito** [comment]
@featherplain @taroooo2o8 
https://github.com/wct2016/wct2016/blob/develop/src/scss/style/_timetable.scss#L75
いまはスラッグに `10min` が入っていると「5分」というラベルが出るようになってます。

wcb-session-head-first-woocommerce-20min

上記のようなスラッグにすると、ラベルが出るわけですね。

似たような感じで、セッション名のあとになんか出すとか、そういうのは可能ですよ。

ただ、カテゴリがないので、各セッションを判別する方法はスラッグしかないので、排他的なカテゴリにするとよいのでは？

wcb-session-head-first-woocommerce-20min-c1001

**Comment by taroooo2o8** [comment]
@featherplain @fumikito
こちらやってみようと思うんですがセッション時間の表記と一緒で「_timetable.scss」
を修正すればいいんでしょうか？

**Comment by featherplain** [comment]
@taroooo2o8 

作業ブランチ: develop を pull した後に、develop から feature/timetable-category の名前で切ってください

> セッション時間の表記と一緒で「_timetable.scss」
> を修正すればいいんでしょうか？

はい、同じ方法で大丈夫です。
https://github.com/wct2016/wct2016/blob/develop/src/scss/style/_timetable.scss#L75
を参考にするといいかと!

> ただ、カテゴリがないので、各セッションを判別する方法はスラッグしかないので、排他的なカテゴリにするとよいのでは？
> 
> wcb-session-head-first-woocommerce-20min-c1001

文樹さんが言っているように、WordCamp サイトのセッションにはカテゴリの機能がないので、スラッグでの判別になります。 カテゴリはとりあえずこんな感じでお願いします ↓

---

## 初心者向け
- スラッグ: beginners
- 説明: WordCamp Tokyo や WordPress が初めての方にオススメのセッションです。

例えば `google-search-trend-20min` というセッションスラッグがあるとしたら、スラッグの末尾に `beginners` をつけて `google-search-trend-20min-beginners` にする

![image](https://cloud.githubusercontent.com/assets/7019355/18576169/12a79474-7c1a-11e6-9af7-3675daabd157.png)

セッション編集画面のパーマリンクを編集してください。

### 対象のセッション
- 夢をかなえるWordPress
- Change! LTであなたも変わろう！
- 公務員を辞めた私がオープンソースを志向した理由
- WordPress初心者が試みる「男木島図書館」の情報発信
- ワークフローとしてのオープンソース
- WordPressで運営する大手メディア 座談会

## オススメ
- スラッグ: recommend
- 説明: WordCamp Tokyo スタッフイチオシのセッションです。当日何を聞くか迷ったら、これを聞けばまちがいなし!

例えば `first-woocommerce-20min` というセッションスラッグがあるとしたら、スラッグの末尾に `beginners` をつけて `first-woocommerce-20min-recommend` にする

### 対象セッション
- CMS四天王への攻撃デモを通じて、WordPressの効果的な防御法を学ぼう
- Contributing, You, and your Business / 貢献すること、あなた自身のこと、あなたのビジネスのこと
- Google 検索モバイルトレンド: モバイルサイトを AMP でもっとサクサク高速に
- WordPressで運営する大手メディア 座談会

**Comment by featherplain** [comment]
@taroooo2o8 

## データ

データが必要なので、作業着手前に以下の xml ファイルをインポートしてください。
管理画面の [ ツール ] -> [ インポート ] の WordPress を選んでください。

本番の WordCamp サイトから落としたデータなので、内容に差異は発生しません。
- speakers.xml
- sessions.xml
- pages.xml

https://drive.google.com/drive/folders/0BwKFWacVUxTpRFdmN3U5OHlmTU0

↑ここから落としてください!
Google Drive の [ WCT2016_Web制作班 ] -> [ data ] の中です

**Comment by featherplain** [comment]
@taroooo2o8 

## 仕上がりイメージ

イメージがあった方が作業しやすいかと思うので、作りました。
マージンとかはなんかいい感じにしてください(雑ですみません)

![image](https://cloud.githubusercontent.com/assets/7019355/18576769/8471f748-7c1f-11e6-8864-4a489cf0820e.png)

### CSS

#### アイコン

ハートと星のアイコンは、[Dashicons](https://developer.wordpress.org/resource/dashicons/#editor-strikethrough) を使ってください。

WordPress の管理画面の [ 外観 ] -> [ Fonts ] で [ Dashicons をエンキューする ] にチェックを入れると使えます(本番では有効化済み)。あとは [CSS の mixin を include](https://github.com/wct2016/wct2016/blob/develop/src/scss/core/_mixins.scss#L106) すれば楽だと思います。

#### カテゴリの角丸とフォントのスタイル
- 背景色: #ff814e
- border-radius: 25pxくらい
- color: #fff
- フォントサイズ: 12px

**Comment by taroooo2o8** [comment]
分かりやすいです！ありがとうございます

**Comment by featherplain** [comment]
@taroooo2o8 

## 補足

ローカルでの作業段階では `オススメ` と `初心者向け` それぞれひとつづつ、作業用&確認用につけてあげればいいので、対象セッションの全てにカテゴリをつけなくても大丈夫です。全部つけるのはめんどくさいかと思うので^^;
