### ISSUE TITLE
チケット申し込みの所の価格の小数点をなくす

### ISSUE THREAD

**Issue by taroooo2o8** [wct2016/wct2016#113]

**Comment by featherplain** [comment]
@taroooo2o8 可能ならそのままお願いしたいです(><)

**Comment by taroooo2o8** [comment]
@naokomc そのままでいいでしょうか？

**Comment by featherplain** [comment]
@taroooo2o8 @naokomc あ、そういう意味じゃなくて、対応可能ならそのまましんちゃんに作業お願いしたいという意味です! (ややこしくてすいません)

**Comment by taroooo2o8** [comment]
@featherplain 
あ、了解です！
今修正してみたんですが、githubの使い方がイマイチなので少々お待ち下さい

**Comment by fumikito** [comment]
@featherplain @taroooo2o8 
これ直せないんじゃない？　CSSでテキストノードを操作するのは無理だよね？

**Comment by featherplain** [comment]
@taroooo2o8 @fumikito 無理でした...

**Comment by naokomc** [comment]
こっちのほうで直してくれる方がいれば…、いつの日か… 😭 
https://github.com/Automattic/camptix/issues/141

↑ イシュー内のリンクによると韓国、チリ、ベトナムあたりも困っちゃう模様ですが最近 WordCamp やっていない…。それ以外の国はかなりマイナー。
