### ISSUE TITLE
facebookカバー画像の編集

### ISSUE THREAD

**Issue by misha-endo** [wct2016/wct2016#12]
> 可能なら、この右側のシルエットのワプーが正方形のアイコン部になると良いかなと思います。

とご意見いただいていて
カバー画像がワプーなしで、シルエットのFBアイコン画像も作成をお願いしてもよろしいでしょうか？

**Comment by osugi0107** [comment]
@misha-endo 
なるほど！そのほうが良さそうですね。対応します！

**Comment by misha-endo** [comment]
@osugi0107 ありがとうございます。
お時間などは大丈夫ですか？

また、こういう場合にほかの人でも対応できるように、psdもドライブにアップロードいただいてもよろしいですか？

**Comment by osugi0107** [comment]
@misha-endo 
大丈夫です。すぐ対応します。
psdの件、了解しました！一応常に最新版を上げてはあります！

**Comment by misha-endo** [comment]
@osugi0107 ありがとうございます。ありました！！

**Comment by osugi0107** [comment]
@misha-endo 
今、修正版をアップしました！あと若干、タイポの位置を調整しました。
psdも最新版になっています。よろしくお願いします！

**Comment by misha-endo** [comment]
@osugi0107 ありがとうございます〜。しかもaiでした〜。ごめんなさい。

**Comment by osugi0107** [comment]
aiでしたねw こちらこそ失礼しました！

**Comment by misha-endo** [comment]
@osugi0107 いえいえ。あの、closeしちゃったんですが、ワプーのアイコンもおねがいできますか？

すでにあったらすいません

**Comment by osugi0107** [comment]
@misha-endo 了解です。アイコンも作成しますね！

**Comment by misha-endo** [comment]
@osugi0107
ありがとうございます

**Comment by osugi0107** [comment]
@misha-endo 
アイコン作成しましたー！
`2016-wpct/2016_FB_icon/` へアップしましたので、ご確認ください。

**Comment by misha-endo** [comment]
@osugi0107 ありがとうございます！！
確認させていただきます。

**Comment by misha-endo** [comment]
@osugi0107 紺色にされたんですね〜。ありがとうございます。
これで、送ります〜

**Comment by osugi0107** [comment]
@misha-endo 
アイコンだけ黒ですと少し浮くので、
カバー画像の建物の色と統一してみました〜
気になるようでしたら修正致しますのでご連絡ください！

**Comment by misha-endo** [comment]
@osugi0107 今試しに仮にのせてみたのですが、良い感じだと思います。
ありがとうございます。

![2016-03-03 3 41 42](https://cloud.githubusercontent.com/assets/12777029/13486704/89ec5826-e156-11e5-9264-12dabf4819bb.png)

**Comment by osugi0107** [comment]
@misha-endo 
了解です！また何かありましたらご連絡ください！

**Comment by misha-endo** [comment]
@osugi0107 
ありがとうございます。
引き続き、よろしくお願い致します。
