### ISSUE TITLE
アンケートのお願い

### ISSUE THREAD

**Issue by misha-endo** [wct2016/wct2016#13]
WCT2016_Web制作班のスプレットシートのアンケートシートの記入をお願い致します。
各自、記入が終わりましたら下記のチェックボックスにチェックをお願い致します。

4/11の本サイト公開にあたり制作が本格化するので、参考までにご協力ください。

シート内の `自由記入欄` は任意です。
技術的に不安な点など、何かあれば自由にコメントしてください。

**期限：3/13（日）**
- [x] @osugi0107 
- [x] @featherplain 
- [x] @momonotsubo 
- [x] @taroooo2o8

**Comment by osugi0107** [comment]
@misha-endo アンケート回答しましたー！

**Comment by momonotsubo** [comment]
@misha-endo アンケート回答しました！よろしくお願いします！

**Comment by taroooo2o8** [comment]
@misha-endo

回答しましたー！

**Comment by misha-endo** [comment]
@osugi0107 @momonotsubo @taroooo2o8 返信が遅くすいません。

ありがとうございます。
