### ISSUE TITLE
スポンサー班確認事項

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#21]
- スポンサーランクの種類
- スポンサーロゴのサイズの種類
- テキストリンクになるランクはあるか?
- [ ] 確認出来次第、スプレッドシートの [スポンサー] シートの内容を更新

**Comment by naokomc** [comment]
**スポンサーランクの種類**
1. グローバルスポンサー (Global Community Sponsorship)
   - ゴールド (Gold)
   - シルバー (Sliver)
   - ブロンズ (Bronze) 
2. ローカルスポンサー
   - Tokyo ゴールドスポンサー (Tokyo Gold) ¥500,000
   - Tokyo シルバースポンサー (Tokyo Sliver) ¥300,000
   - Tokyo ブロンズスポンサー (Tokyo Bronze) ¥100,000
   - マイクロスポンサー（テキストリンク）¥10,000

になります。
ロゴのサイズですが、グローバルのゴールドと Tokyo ゴールドは同じ、という感じでロゴありのスポンサーは3段階。マイクロスポンサーは全ページのフッターなどではなく、別途ページに一覧表示のみ。という感じでお願いします（マイクロスポンサーは、通常チケットの代わりに寄付つきの高めのチケットを購入していただく感じで、通常のスポンサーという扱いとはやや異なります）。

今後、他の班からの情報が必要なタスクがあれば私にアサインしてください。よろしくお願いします。
