### ISSUE TITLE
パターンの元データ共有のお願い

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#23]
@natsumiine

 ![image](https://cloud.githubusercontent.com/assets/7019355/16326283/2aedbbd2-3a00-11e6-827c-17ec3c6382e0.png)
 ![image](https://cloud.githubusercontent.com/assets/7019355/16326284/33899f72-3a00-11e6-82d8-6acb2c0e7a2b.png)
1. メイン画像のパターンの元が見つからず、コーディング用に書き出しができないのでパターンの元データをください。
2. ナビゲーション、フッター等で使用されている市松模様のパターンも同様にお願いします。

**Comment by ghost** [comment]
@featherplain GoogleDriveに、AI(pattern_mainの元)、PSD(書き出し用データ)、PNGの3種類を入れておきましたー！
