### ISSUE TITLE
サイドバー掲載用バナー修正

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#24]
@natsumiine

バナーの WordCamp Tokyo の表記についてです。

```
Word
Camp
Tokyo
```

改行されてになっているので

```
WordCamp
Tokyo
```

に修正お願いします。

バナーだけ別途 PSD データにしてあげて貰えると嬉しいです!

**Comment by ghost** [comment]
@featherplain 修正してGoogleDriveにあげておきましたー！
さきほど共有したURLからみられます！
