### ISSUE TITLE
[ コーディング ] スポンサーエリア 

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#29]
関連: #77 

フッターのスポンサーエリアのスタイリングをする
コンテンツは WordCamp のスポンサー用ウィジェットで出力するかも(去年・おととしは全部手動)

![image](https://cloud.githubusercontent.com/assets/7019355/16327388/5d43fc0a-3a09-11e6-954d-51b8e20e5b15.png)
## スポンサーランク

https://github.com/wct2016/wct2016/issues/21#issuecomment-226980922

**Comment by misha-endo** [comment]
@featherplain 決起集会にてスポンサーエリアについてはスポンサー班が行ってくれるということでした。
制作班としては、
テンプレートと画像のサイズを指定してほしいとのことでした。
（後ほど確認させてください。）

**Comment by featherplain** [comment]
@misha-endo 
#77 にスポンサーロゴ掲載についてまとめました。

> テンプレートと画像のサイズを指定してほしいとのことでした。

テンプレートは、何のことを指しているのでしょうか?
