### ISSUE TITLE
スポンサーページ作成

### ISSUE THREAD

**Issue by misha-endo** [wct2016/wct2016#3]
- 固定ページ作成
- 募集要項のひな形のマークアップ

**Comment by featherplain** [comment]
- 期限はいつでしょうか?
- 作業完了後の Assignee を誰にするか記載お願いします。
- 直接 2016.tokyo.wordcamp.org にログインして作業ですかね?
- マークアップ時に入れる内容は、ダミーでいいでしょうか?
- 作業が完了したら、どうすればいいでしょうか? 班長のチェックがあるから 下書きで保存 かな?
- スポンサー募集ページのスラッグはどうしましょう?
- 作業時に参考にするといいものを教えて下さい! 例えば去年の開催概要のページの URL を記載するとか

**Comment by featherplain** [comment]
↑ @misha-endo 確認お願いします

**Comment by misha-endo** [comment]
期限 : 2/25
作業完了後 Assignee :  遠藤

マークアップ時に入れる内容は、ダミーでいいでしょうか?
＞ダミーでお願い致します。

直接 2016.tokyo.wordcamp.org にログインして作業
＞相談させてください

作業が完了したら 下書きで保存かどうか
＞直接でなく、別で環境構築した場合はベーシック認証をつけるかなどで判断させてください

開催概要ページのスラッグ
＞去年と同じでもよいかと思うのですが、これは制作班の権限できめてもよいのでしょうか？

参考に去年のスポンサーページのページの URL を記載
＞去年の初期段階のページはまだのこっているのでしょうか？
＞勉強不足ですいません

**Comment by taroooo2o8** [comment]
期限：2/25→2/28
申し訳ありません。期限を今週中に変更させて頂きます。

**Comment by taroooo2o8** [comment]
完了しました！

**Comment by taroooo2o8** [comment]
@misha-endo 
@featherplain 

遅くなってしまい申し訳ないです。
こちら修正しましたのでご確認よろしくお願いします。

https://2016.tokyo.wordcamp.org/sponsors/?preview_id=10&preview_nonce=b7dc0d445b&preview=true

**Comment by featherplain** [comment]
@misha-endo 
@taroooo2o8 

スポンサー応募フォームは iframe で埋め込んでくれているようですが、フォーム入力しやすいようにリンクを貼って Google フォームに飛ばす形はどうでしょう?

**Comment by misha-endo** [comment]
@featherplain
@taroooo2o8 
そうしましょう。今フォームのリンクを依頼しています。
