### ISSUE TITLE
配布用 Facebook カバー画像作成

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#34]
担当者: **未定**
期限: 7/25
## 必要な要素
- WordCamp Tokyo 2016
- 会場名: ベルサール新宿グランド 5F コンファレンスセンター
- 日程
- わぷー
- 各属性ごとの文言 -> `種類` を参照
## サイズ

`851x315`
## 形式

png
## 種類
- WordCamp Tokyo 2016に参加します! ( 参加者向け )
- WordCamp Tokyo 2016を応援しています! ( スポンサー・誰でも向け )
- WordCamp Tokyo 2016に登壇します! ( スピーカー向け )
- WordCamp Tokyo 2016を運営しています! ( スタッフ向け )
## 参考

https://2015.tokyo.wordcamp.org/fb_cover/

**Comment by featherplain** [comment]
@misha-endo 会場名を入れる場合は、「ベルサール新宿グランド 5F コンファレンスセンター」としてください。

**Comment by misha-endo** [comment]
![2016-07-18 2 07 28](https://cloud.githubusercontent.com/assets/12777029/16901957/818fdd3c-4c8c-11e6-9686-0af3c110b772.png)

種類の「WordCamp Tokyo 2016を〜」のテキストは一旦重複するので省きました。

こんなかんじはいかがでしょうか？

**Comment by featherplain** [comment]
@misha-endo 
よいですよいです!!!!! ありがとうございます。
データを GitHub にあげてもらえますでしょうか?
https://github.com/wct2016/fb-cover にリポジトリは作ってあります。
- 元の PSD (モックアップにはいれてなくて OK)
- 書きだした png 画像
  を含めておいてください。

**Comment by misha-endo** [comment]
@featherplain 今、pushしたんですがすいません。jpgでpushしてしまったんですがpng のほうがよろしいでしょうか？

**Comment by misha-endo** [comment]
@featherplain 確認ありがとうございます！！！良かったです！

**Comment by featherplain** [comment]
@misha-endo 
https://github.com/wct2016/wct2016/issues/34#issue-162831943
Issue は読んでくれてますでしょうかー?
形式は png と記載してますので、png にしてください。
