### ISSUE TITLE
配布用バナー作成

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#35]
担当者: @natsumiine
昨年度: https://2015.tokyo.wordcamp.org/banners/
期限: Milestone の通り、7/25 (もし、7/17に間に合えば、嬉しい!)
- 例年バナーとして作成してきたが、サイズこだわらなくてもいいかも
- WCEU のようにバッジ風も素敵: https://2016.europe.wordcamp.org/get-a-wceu-badge-for-your-website/
- 余裕があれば英語表記版も作成したい
## 種類
1. バッジ
2. 長方形 (`728x90` だとブログ記事内で使いやすいかも)
3. バッジ英語

の優先順位
## データのアップ先

バナーができたら、一旦 この Issue に画像を貼り付けてほしいです。
完成版を https://github.com/wct2016/banners にアップできればと思います。

**Comment by ghost** [comment]
@featherplain 
![wvt2016_badge](https://cloud.githubusercontent.com/assets/8974150/16896333/64817b2c-4bcb-11e6-8b7c-d35e917cb7e9.png)

バッジ、こんな感じでどうでしょう！

**Comment by featherplain** [comment]
@natsumiine 
とてもよいです!!!!!!!!!!!!!!

**Comment by featherplain** [comment]
@natsumiine 
すみません、デザインに関しては OK なのですが、
サイト公開にあたって、トップ画像の会場名を「ベルサール新宿 5F コンファレンスセンター」に変更したほうがいいと指摘をもらったので、バナーも合わせて変えてもらえますでしょうか?
https://github.com/wct2016/wct2016/issues/62#issuecomment-233171201

**Comment by ghost** [comment]
@featherplain 
![wct2016_banner](https://cloud.githubusercontent.com/assets/8974150/16901938/1a249e62-4c8c-11e6-9119-c5b416c500cc.png)
![wct2016_banner_lec](https://cloud.githubusercontent.com/assets/8974150/16901940/200534c2-4c8c-11e6-9cc7-645c80e0348c.png)
![wct2016_badge](https://cloud.githubusercontent.com/assets/8974150/16901941/28a4895c-4c8c-11e6-9bb5-0f94fd880360.png)

修正＆長方形バナー作りましたー！👹✨

**Comment by featherplain** [comment]
@natsumiine ありがとうございます!!!!! めちゃよいですね!!!!
そしたら、完成版バナーを GitHub にあげてもらえるでしょうか...?
元の AI (PSD) と書きだした png があれば OK です。
リポジトリはもう作ってあるので、  https://github.com/wct2016/banners です。

**Comment by ghost** [comment]
@featherplain ローカルからこのリポジトリにpushを試みてるんですが、アクセス拒否されてしまって取り込めず…(：д；)

**Comment by featherplain** [comment]
@natsumiine 多分、メンバーじゃないからかもしれないです。以前招待メール送ったのですが、もし過去のめーる辿って見つからなさそうなら再度招待するので Slack でメールアドレス教えて下さい! :bow:

**Comment by ghost** [comment]
@featherplain すみません〜招待メール発掘できなかったのでもう一度送っていただけると助かります！！🙇💦
