### ISSUE TITLE
配布用バナーページ作成

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#36]
関連: #35 
担当者: @misha-endo 

バナーができてないのですが、先にページ作成をお願いできますか? 内容は下記です。
## 作業内容

配布用バナーページの作成をする
- バナー画像はできていないので、画像の部分は内容空のままで OK
- フォーマット、マークアップは去年と同じで OK
- Markdown での作成可
  - ただし、定義リスト `<dl>` は Markdown が効かないので HTML 
## 作業方法
- WordCamp サイトで直接作業
- 作業が終わったら下書き保存
## 注意

```
公式 Facebook カバーもあります!

WordCamp Tokyo に参加する人、応援してくれる人は Facebook 公式カバーもぜひ利用ください!
以下のブログ記事から入手できます。

公式 Facebook カバーをぜひご利用ください!
```

まだ FB カバーできていないので、上記は無しで
## 参考

昨年度: https://2015.tokyo.wordcamp.org/banners/

**Comment by misha-endo** [comment]
@featherplain こちらですが、ステージングでよいですよね。。こちらすいませんユーザーはパスワードを発行いただいてもよろしいでしょうか？

**Comment by featherplain** [comment]
@misha-endo 本番サイトで直接作業してもらって OK です!

**Comment by misha-endo** [comment]
@featherplain 了解です。ありがとうございます！

**Comment by misha-endo** [comment]
@featherplain 固定ページに配布バナーというタイトルで作ってあります。（今は画像がまだということでしたのでほぼ去年のをもってきただけの状態です。）

**Comment by featherplain** [comment]
@misha-endo ありがとうございます。

こちらでスラッグを足したのと、FB カバーの箇所を削除しました。
ステータスは下書き保存にしておきました。
