### ISSUE TITLE
サイトのデフォルト画像作成と設定

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#37]
- 担当者: @misha-endo 
- 期限: 7/17 が望ましいですが、他に優先タスクがあればそちらを着手してください。7/25がデッドラインです。
## 作業内容

ファビコンのデザイン作成と WordCamp サイトへの設定
## サイズ

`512x512`
## 形式

`.ico` でなくて OK です。png がいいかと思います。
※ ちなみにWordPress 上ではファビコンのことをサイトアイコンと呼んでいます。

去年は書道家わぷーが持ってる筆をファビコンにしました。
![image](https://cloud.githubusercontent.com/assets/7019355/16794319/0c4b9282-4912-11e6-9f7c-ac77413cee6b.png)
### WordCamp サイトへの設定方法

[ 外観 ] -> [ カスタマイズ ] -> [ サイト基本情報 ] にて設定

**Comment by featherplain** [comment]
@misha-endo 
追記です。
- サイズは description に明記してあるように、 `512x512` の1種類で OK
- 画像が作成できたら、一旦見せてください。

**Comment by misha-endo** [comment]
@featherplain 制作班ドライブの favicon/ の中に画像を格納いたしました。apple touchアイコンも用意してみました。よろしくお願いいたします。

**Comment by featherplain** [comment]
@misha-endo 
ありがとうございます! デザインいい感じです。

ところで、Issue の[内容](https://github.com/wct2016/wct2016/issues/37#issue-163077462)や[追記のコメント](https://github.com/wct2016/wct2016/issues/37#issuecomment-232620122)は読んでくれていますか?
サイズは `512x512` です。それ以外は必要ありません。書き方がよくなかったですが、`.ico` も不要。

`512x512` のサイズだけ作って、今アップロードしてもらった画像は全て削除してください。readme.txt  も不要です。お手数おかけしますが、よろしくお願いします。

**Comment by misha-endo** [comment]
@featherplain 気を回したつもりがいりませんでしたね。すいませんm(_ _)m直しました。よろしくお願いいたします。

**Comment by featherplain** [comment]
Facebook の OGP 画像の依頼(@小杉さんより)
https://github.com/wct2016/wct2016/issues/62#issuecomment-233525862

Facebook でサイトのシェアした場合の OGP 画像はサイトアイコンが表示されるようなので、
OGP 表示を考慮したデザインで作りなおした方がいいかも

![image](https://cloud.githubusercontent.com/assets/7019355/16908437/9385358a-4d06-11e6-8ee4-9ab419945715.png)

背景色つきの正方形でつくると良さそう

## 例: WCEU の場合

サイトアイコン
![image](https://cloud.githubusercontent.com/assets/7019355/16908647/3d18f766-4d08-11e6-8cd1-8c1bf9475edf.png)

OGP 画像
![image](https://cloud.githubusercontent.com/assets/7019355/16908638/2c5368bc-4d08-11e6-9af3-893b1d7861a7.png)

**Comment by featherplain** [comment]
@misha-endo 
せっかくファビコン作ってもらって申し訳ないのですが、画像を作りなおしてもらうことはできますか?
サイズは `512x512` 以上、背景色つきの正方形でつくると良さそうです。

ファビコン向けのシンプルで分かりやすいデザインというよりも、OGP を意識したデザインにしてもらうのがいいと思います。

経緯は https://github.com/wct2016/wct2016/issues/37#issuecomment-233258013 を参照してください。

**Comment by mekemoke** [comment]
OGPはサイトアイコンとは別に設定できるので、1200x630で作っていただけるとありがたいです！
ファビコンとは別でも大丈夫ですよー！

**Comment by featherplain** [comment]
@misha-endo @mekemoke さんのコメントの通りなので、作りなおさなくても大丈夫そうです。Issue クローズします!
