### ISSUE TITLE
アクセスページの作成

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#38]
@naokomc 

時期的にアクセスページがあっても良さそうな気がするので、会場班の方に内容作成してもらってもいいでしょうか。
## 公開時期

テーマビジュアル公開(7/17頃)と同時にページ公開できるように考えていますが、原稿ができ次第ページつくって公開しようと思います。
## 内容について

フォーマットは去年のものと同様でいいかと思います。
https://2015.tokyo.wordcamp.org/location/
※ Google Map は Web 班で用意します

もしできれば、空港からのアクセスや、新幹線からのアクセスもあると嬉しいです。
## 原稿形式

Markdown 形式で貰えると作業しやすいので助かります!

---

ちなみに、ビジュアル公開時点でのサイトマップ(予定)はこちらですー。
https://github.com/wct2016/wct2016/wiki/sitemap

**Comment by naokomc** [comment]
会場班グループで担当してくれる方がいるかどうか聞いてみました。

（余談）7/6に会場班と一緒に下見に行くので、更新班からリクエストがあった駅からのアクセス写真を撮って渡し、記事にしてもらう予定です（こちらはアクセスページではなくてブログ）。

**Comment by naokomc** [comment]
今週末くらいまでに会場班のちくちゅう（竹中）さんが作成してくださるとのことです。

**Comment by featherplain** [comment]
@naokomc ありがとうございます!

**Comment by chikuchu** [comment]
遅くなりました。
こんな感じでどうでしょうか。

Markdownで作ったのはじめてなんで間違いがあれば修正またはご指摘お願いします。
[WCT2016_access.txt](https://github.com/wct2016/wct2016/files/362739/WCT2016_access.txt)

**Comment by chikuchu** [comment]
@featherplain 
遅くなりました。
こんな感じでどうでしょうか。

Markdown形式で作成したの初めてなので、間違いがあれば修正いただくか、ご指摘ください。
[WCT2016_access.txt](https://github.com/wct2016/wct2016/files/362743/WCT2016_access.txt)

**Comment by featherplain** [comment]
@chikuchu ありがとうございます! こちらを元に、アクセスページ作成させていただきますー!
