### ISSUE TITLE
[ 会場について ] の作成

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#39]
@naokomc 

こちらも #38 同様会場班に依頼をお願いしたいです。
## 内容

会場について
https://2015.tokyo.wordcamp.org/location/notes/

昨年度はこんな感じでした。
乳幼児連れても大丈夫かどうかの質問をどこかで見かけたような気がするので、乳幼児や子連れに関する内容も明記すると、今後サイトを見る人に親切かなと思います。
## 形式

Markdown 希望です。

---

こちらは7/17の時点で出せるものがあれば進めて、順次アップデートできればと思います。
まだ早ければ時期を見て再度依頼を出します!

**Comment by naokomc** [comment]
7/6下見の後に、できるだけ早く部屋の利用法を決定します。その後情報をお渡ししする流れで。

**Comment by naokomc** [comment]
# 施設に関して

## 利用可能エリア
- 9/17: 5階全フロア
- 9/18: 5階 Room G・H

※ 会場エリア以外のご利用はご遠慮ください。

## 会場内での飲食について

各ルーム内での飲食は可能ですが、ロビーおよび廊下では一切ご飲食はいただけません（懇親会開催中も含む）。また、セッション中は匂いや音が出るものなどはご遠慮ください。

### 休憩・食事スペース

Room I に休憩用のスペースをご用意いたしましたので、ご利用ください。乳児とお母様には控室1（授乳室）、その他小学生以下のお子様連れの方は控室2も合わせてご利用いただけます。
※ 9/17のみ
- フロア内に自動販売機エリアが2ヶ所ございます。
- 飲食物のお持ち込みも可能です。
- ゴミは各自お持ち帰りください。

## 喫煙所

喫煙所を2ヶ所設けております。それ以外での喫煙はご遠慮ください。

## フロアマップ

![v2](https://cloud.githubusercontent.com/assets/34067/16794999/e3756492-4915-11e6-961d-0f538a5c7bea.png)

## ネット回線 / 電源
- 当日は、フリー Wi-Fi の提供を予定しております。回線利用が想定より多い場合、回線の安定性を保つ為、一部制限を掛けさせていただく場合がございますので、予めご了承ください。
- 電源については、電源サービスエリアを若干ご用意しております。ただし、数に限りがございますので必ずしも電源確保のお約束はできません。譲り合ってご利用ください。
- 会場提供のネット回線や電源に不安がある方は、ご自身でポケット Wi-Fi や充電器などをお持ちください。

## 写真 / 動画撮影
- 運営側での記録の為に写真撮影、またセッションの録画・公開を行います。会場内でのスナップ撮影について故意に来場者の顔をアップで写したりはしませんが、写真内に映り込む可能性がございますのでご了承下さい。
- 運営側で撮影した写真は公式サイトなどで公開します。もし写真の削除を希望される場合は、公式サイト内お問い合わせフォームよりご連絡下さい。
- 壇上にいる講演者、イベントTシャツを着たスタッフ以外の方が写っている写真をオンラインなどで共有する場合は、問題がないかどうか事前に本人に確認していただくようお願い致します。

## その他
- ご不明な点は入り口付近の「インフォメーション」までお問い合わせください。
  万一の災害時においては、スタッフの指示誘導に従って速やかに行動をしてください。
- 怪我、事故、盗難、その他のお客様同士のトラブルについて、WordCamp Tokyo 2016 実行委員会は一切責任を負えませんのでご了承ください。

会場へのアクセス方法はこちらをご覧ください。

**Comment by featherplain** [comment]
@naokomc ありがとうございます!!!

**Comment by naokomc** [comment]
フロアマップ完成ではないので、こちらは少々お待ちください〜
