### ISSUE TITLE
開催概要ページ作成

### ISSUE THREAD

**Issue by misha-endo** [wct2016/wct2016#4]
- 固定ページ作成
- 開催概要のひな形のマークアップ

**Comment by featherplain** [comment]
@misha-endo 
- 期限はいつでしょうか?
- 作業完了後の Assignee を誰にするか記載お願いします。
- 直接 2016.tokyo.wordcamp.org にログインして作業ですかね?
- マークアップ時に入れる内容は、ダミーでいいでしょうか?
- 作業が完了したら、どうすればいいでしょうか?
  班長のチェックがあるから `下書きで保存` かな?
- 開催概要ページのスラッグはどうしましょう?
- 作業時に参考にするといいものを教えて下さい! 例えば去年の開催概要のページの URL を記載するとか

**Comment by misha-endo** [comment]
期限 : 2/25
作業完了後 Assignee :  遠藤

マークアップ時に入れる内容は、ダミーでいいでしょうか?
＞ダミーでお願い致します。

直接 2016.tokyo.wordcamp.org にログインして作業
＞相談させてください

作業が完了したら 下書きで保存かどうか
＞直接でなく、別で環境構築した場合はベーシック認証をつけるかなどで判断させてください

開催概要ページのスラッグ
＞去年と同じでもよいかと思うのですが、これは制作班の権限できめてもよいのでしょうか？

参考に去年の開催概要のページの URL を記載
＞去年の初期段階のページはまだのこっているのでしょうか？
＞勉強不足ですいません

**Comment by momonotsubo** [comment]
@featherplain 確認しました！ページのレイアウトとかがわからないので、班長に聞いているところです。そもそも、2016.tokyo.wordcamp.org ログインして作業が……メールが来ていないので、ログイン出来ないかと思われます。。まだ、マークアップも固定ページ作成もどう進めて良いか分からず、班長に聞いたまんまで、止まっている状況です。期限は、27日では厳しいでしょうか？

**Comment by featherplain** [comment]
@momonotsubo
確認ありがとうございます! 
WordPress のアカウントは私の方で発行します! 別途 Slack でやりとりしましょうー。

大丈夫だとは思いますが、一応遠藤さん @misha-endo  に聞いてみましょう。

**Comment by featherplain** [comment]
## div 要素

空の `div` 要素が気になりました。
```
<section>

  <div> // 空の div は意図的?
    .
    .
    (略)
    .
    .
    <div> // 空の div は意図的?
    </div>
  </div>
</section>
```

## セクションを分ける

開催概要とコンセプト文の内容の性質上、`section` は分けた方がいいと思います。
```
<section>
  <h2>今年も WordCamp Tokyo を開催します!</h2>
  (内容略)
</section>
<section>
  <h2>開催概要</h2>
  (内容略)
</section>
```

## WordCamp とは? の文章に関して

### ページを分ける
コンセプト -> 開催概要 の流れで、いきなり WordCamp の説明が来るのは違和感を感じるので、
昨年のように WordCamp とは? のページを作ってしまってもいいんじゃないでしょうか。
文章量的にもひとつのページにまとまると長くなりますしいかがでしょうか?
https://2015.tokyo.wordcamp.org/what-is-wordcamp/

### ページヘのリンクを設定
コンセプト文の冒頭に
>WordCamp とは: 世界シェア No.1 であるオープンソース CMS「WordPress」の普及促進と情報交換を目的と...(以下略)

とあったので、[ WordCamp とは ] の箇所に [ WordCamp とは? ] リンクをはると、よりいいと思います!

**Comment by featherplain** [comment]
@misha-endo 
@momonotsubo 

## div 要素

空の `div` 要素が気になりました。

```
<section>

  <div> // 空の div は意図的?
    .
    .
    (略)
    .
    .
    <div> // 空の div は意図的?
    </div>
  </div>
</section>
```

## セクションを分ける

開催概要とコンセプト文の内容の性質上、`section` は分けた方がいいと思います。

```
<section>
  <h2>今年も WordCamp Tokyo を開催します!</h2>
  (内容略)
</section>
<section>
  <h2>開催概要</h2>
  (内容略)
</section>
```

## WordCamp とは? の文章に関して

### ページを分ける

コンセプト -> 開催概要 の流れで、いきなり WordCamp の説明が来るのは違和感を感じるので、
昨年のように WordCamp とは? のページを作ってしまってもいいんじゃないでしょうか。
文章量的にもひとつのページにまとまると長くなりますしいかがでしょうか?
https://2015.tokyo.wordcamp.org/what-is-wordcamp/

### ページヘのリンクを設定

コンセプト文の冒頭に

> WordCamp とは: 世界シェア No.1 であるオープンソース CMS「WordPress」の普及促進と情報交換を目的と...(以下略)

とあったので、[ WordCamp とは ] の箇所に [ WordCamp とは? ] リンクをはると、よりいいと思います!

**Comment by momonotsubo** [comment]
@misha-endo @featherplain　修正内容確認して、修正しました。

## WordCamp とは? の文章に関して

一応、固定ページ作成して、下書き保存してますので、ご確認お願いします。

**Comment by misha-endo** [comment]
@momonotsubo ありがとうございます。
確認しますね。
