### ISSUE TITLE
参加登録ページ作成準備

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#40]
詳細はこちらの description にまとめる
今分かっていること: 一般1000円、Tシャツ付き3000円、マイクロスポンサー1万円

Camptix 使用の場合、Web 班で Camptix の設定をし、必要に応じて委員長 / 副委員長に確認する

**Comment by featherplain** [comment]
@naokomc 今年も去年と同様、チケットは Camptix による決済で OK ですか?

**Comment by featherplain** [comment]
@naokomc 
内容がたくさんで申し訳ないですが、詳細&質問事項をまとめました。

関連: #47 参加登録ページ作成

チケットと参加登録ページは WordPress で下書き保存済みです。

## 本サイト公開時点でのチケット

参加登録開始時点では、1日目のみでしょうか?
以下、1日目、2日目含めた質問になります。

## イベント内容について

チケットの description にイベント内容を書きたいので、内容を教えて下さい。
去年は1日目がセッション(+ハンズオン)デイ、2日目はコントリビューターデイとイベント内容がはっきり分かれていましたが、今年も同じでしょうか。 
もしくは、今年の Kansai みたいに1日目も2日目もセッションやハンズオン、コントリビューターデイが混在した形になりますか?

## チケットの参加費について

> 一般1000円、Tシャツ付き3000円、マイクロスポンサー1万円

こちらは1日目の参加費だと思いますが、2日目は無料ですか?
Tシャツのサイズの種類は、参加者が選択できるのでしょうか?

## チケット販売数

全体のチケット販売数( = 会場の定員数)と、各チケットの販売数を把握したいです。
- 1日目
  - 一般
  - Tシャツ付き
  - マイクロスポンサー
- 2日目
- 関係者用無料クーポン[※]

[※] スタッフ、スポンサー(マイクロスポンサー以外)、スピーカーなどの関係者はチケット無料になりますよね? 関係者向けにクーポンコードを発行する必要があります。

### 去年の場合

定員が700名だったので、以下のように進めました。
- 参加登録開始時点では 500 
- クーポンは 150
- 残り販売数 200

ただし全体の販売数500でクーポン150としても、クーポンを使わないチケットが500枚買えてしまうのでそこだけ注意

## 学生など未成年用チケットについて

去年は参加登録開始後に未成年者はチケットどうする?と声があがり、無料になった経緯があります。
年齢が確認できる身分証の提示を条件に、本編・懇親会共に未成年者用(18歳未満)の無料チケットを有料チケットとは別に発行しました。
今年は未成年者の扱いはどのようにしますか? 

ちなみに、無料でなくても「20%割引」といったクーポンの発行も可能です。

## 子連れの場合

質問が来るかとおもうので、乳幼児などの子連れの場合も OK の旨を参加登録ページに記載しておきます。

## クーポンについて

クーポンは複数発行 OK
- wct2015-coupon: 事前スタッフ、スピーカー、スポンサー `150`
- wct2015-lt-speaker: LT 登壇者用 `12`
- wct2015-day-volunteer: 当日スタッフ用 `40`

どういう経緯でクーポンの種類を追加したのか忘れてしまったのですが、昨年度は LT 用と当日スタッフ用を追加しました。例として参考にしてください。

## 返金について
- 返金期限はチケット公開(販売開始)後も変更可能
- Camptix の仕様により、チケット毎に期限の設定ができないので一律になる

今年も去年に引き続き有料となるので返金可能にしたいと思いますが、期限はとりあえず前日までで設定していいですか? 
去年の参加登録開始時点では、開催の1週間前までとしていましたが、後で当日まで返金・キャンセル可に変更しました。

## 参加登録時の質問項目

去年や一昨年は、
- **名前**
- **メール**
- Twitter アカウント
- サイト URL
- 年齢
- 性別
- 過去の WordCamp の参加有無
- 職業

※ 名前とメールは必須

を入力してもらっていましたが、年齢 / 性別 / 職業 / WordCamp 参加有無はなくしてもいかと思っています。昨年はココらへんのデータは特に集計も活用もしなかったので、あまり必要性を感じていません。

なお、コントリビューターデイで .org のアカウントが必要な場合は、新たに項目を設定しますので必要な場合は言ってください。

## 参考

昨年度の Camptix に関するメモ(去年の Backlog の Wiki の内容をコピペ)
https://github.com/wct2016/wct2016/wiki/Camptix-Configuration-in-2015

**Comment by featherplain** [comment]
@naokomc 
去年の参加登録ページです。
https://2015.tokyo.wordcamp.org/tickets/

注意事項は今年もしっかり明記しますが、「参加の流れ」などはなくして、内容を少し簡素化するかもです。

**Comment by featherplain** [comment]
@naokomc 

連投申し訳ないです。
未成年者へのチケットに関して、無料になった理由を今思い出しました。
- [PayPal が20歳以上](https://www.paypal.jp/jp/contents/support/faq/faq-065/)
- クレジットを持っていない場合プリペイド Visa を使用: 18歳以上
- http://vpc.lifecard.co.jp/index.html
- 多くのクレジット会社が18歳以上から

Camptix が PayPal またはクレジット利用のみの決済になるため、すっかり忘れていたのですが18歳未満は必然的に決済が不可能となり、チケットが無料になります。

**Comment by naokomc** [comment]
> 参加登録開始時点では、1日目のみでしょうか?

現在確認中です。

> 去年は1日目がセッション(+ハンズオン)デイ、2日目はコントリビューターデイとイベント内容がはっきり分かれていましたが、今年も同じでしょうか。

今年は1日目がセッション（ハンズオンなし）、2日目はコントリビューターデイ＆ハッカソンになります。

> こちらは1日目の参加費だと思いますが、2日目は無料ですか?

はい、2日目は無料です。

> Tシャツのサイズの種類は、参加者が選択できるのでしょうか?

チケットのアンケートで選択できるようにしていただけると嬉しいです。

> 会場の定員数

1日目は全体で1000人です。が、実質にはスタッフ・スポンサーなど含め来場者予定者が1200人になっても大丈夫だと思います（セッションルーム以外にいる人、当日来ない人がいる想定）。

とりあえずは一般700枚、Tシャツ付き200枚、マイクロスポンサー100枚（計1000枚）で売り出す形ではいかがでしょうか。
Tシャツ付き（マイクロスポンサーも）チケットは、シャツの発注の関係で遅くとも8/17までには締め切る必要があります。そこでまだ定員になっていなければ、一般のチケットを増やしましょう。予算の関係からは、シャツ付きチケットがなるべく多く売れれば楽になります。

関係者のチケットは、クーポン使って無料でOKです。スタッフもTシャツサイズが必要なので、別チケットにした方がいいでしょうか？（一般用のTシャツ付きチケットとは別にしないといけないので）

懇親会は去年 Camptix 使いましたっけ？どちらにしろ本サイト公開時には値段確定しないので、後日販売にはなりますが。

> 未成年者の扱い

小学生以下は完全無料で（懇親会も）。18才以上は一般扱い。
未成年者は17名だったとのことで、保護者などに払ってもらえない場合のみ現金対応ということではむずかしいでしょうか？それでいけそうな場合、中・高生はすべて50%OFFとかを考えています（一般、Tシャツチケット、懇親会。マイクロスポンサーはクーポン適用NG）。
無料にしてしまったほうが楽ということであれば、すべて無料でも！

> 子連れの場合

上記にある通り、乳幼児は無料。今のところ決定しているのは、授乳室と、子供が遊んでもOKなファミリー向け休憩室を設ける（別々の部屋）という点です。

> 返金について

返金期限は前日ではなくて1週間前とかでいいと思います。Tシャツ付きはキャンセルできないほうが理想的ですが…まあ別々にするのもややこしいと思うので。

> 参加登録時の質問項目
> 年齢 / 性別 / 職業 / WordCamp 参加有無

職業属性だけは、セッション班が見ると参考になると思うので残して欲しいです。出身地（県または国）も聞いてみてもいいかもしれません。何県・何ヶ国の人が参加したかわかると面白いので。イベント後のアンケートでは回答率が低く、参加者のことを全般的に理解するのが難しいですよね。でもまあ、年齢、性別、参加有無は、任意回答で残すか、フォームが長くて煩わしければナシで。

> コントリビューターデイで .org のアカウント

こちらもコントリ班に確認中です。

**Comment by featherplain** [comment]
@naokomc 

参加登録ページ下書き
https://2016.tokyo.wordcamp.org/?page_id=537&preview=true
チケット下書き
https://2016.tokyo.wordcamp.org/wp-admin/edit.php?post_type=tix_ticket

**作ったチケット**
`数字` は販売数
- 一般: 当日まで販売 `700`
- 一般Tシャツ付き: 8/17まで販売 `200`
- 未成年: 無料、当日まで販売 `10`
- 未成年Tシャツ付き: 無料、8/17まで販売 `10`
- マイクロスポンサー: 8/17まで販売 `100`

> 関係者のチケットは、クーポン使って無料でOKです。スタッフもTシャツサイズが必要なので、別チケットにした方がいいでしょうか？（一般用のTシャツ付きチケットとは別にしないといけないので）

別チケットにせず [ 一般用チケット ] をクーポン利用してもらうのはどうでしょうか。集計が面倒くさいかもしれませんが、関係者にはサイズを Google フォームなどで別途アンケートとるなどしてもらうことは可能ですか?
- LT登壇者
- 当日スタッフ
- 事前スタッフ、スピーカーやスポンサーの購入忘れ

の存在があり、これらを8/17まですべてカバーできればいいですが、開催までまだ1ヶ月あるので難しいかもしれません。

もしチケットを別途発行するとしたら、関係者用のTシャツつき有料チケットをクーポン使って無料にするのがいいかと思います。
これは考えすぎかもですが、クーポン無しのTシャツつき無料チケットが一般参加者と同列で買えてしまうのは運営上好ましくないかも?と思いました。故意に関係者用無料チケットを一般の方が買う可能性も全くゼロとは言えないので...ちなみに、チケットの出しわけはできなさそうです。

https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/web-presence/using-camptix-event-ticketing-plugin/

> チケットのアンケートで選択できるようにしていただけると嬉しいです。

サイズのアンケートのサイズは S, M, L, XL で仮設定してあります。

> 小学生以下は完全無料で（懇親会も）。18才以上は一般扱い。
> 無料にしてしまったほうが楽ということであれば、すべて無料でも！

https://github.com/wct2016/wct2016/issues/40#issuecomment-232079233
- 小学生以下はチケット登録不要
  - 必然的に保護者同伴になると思うので、保護者がチケット買えばいいかなーと
- 中学生以上の18歳未満は無料チケット

でどうでしょうか?

> Tシャツ付きはキャンセルできないほうが理想的ですが…まあ別々にするのもややこしいと思うので。

Camptix の仕様上、チケットの種類ごとに返金機能や期間の個別設定ができないので一括設定になります。確かにTシャツ付きはキャンセルしてほしくないですよね。

> 職業属性だけは、セッション班が見ると参考になると思うので残して欲しいです。

もろもろ意見ありがとうございます。質問は残して、出身国とお住まいの地域も追加しました。

> 懇親会は去年 Camptix 使いましたっけ？
> 去年は Camptix を使いました。(18歳未満の未成年者は懇親会も無料)

**Comment by featherplain** [comment]
Slack から引用

---

miku_endo [2:10 PM]  
@featherplain: 相談させてください。
以下、内容の依頼がきました。（FBのリーダーズ引用です。）
チケットのこと把握しておらずすいません。こちらは今から間に合うのでしょうか。。
････････････････････････････････････････････････････････････････････････
お疲れ様です。コントリ＆ハッカソンのチケットリリースですが、本サイト公開時に間に合えばお願いしたいです！チケットの数は以下のとおりです。
（コントリとチームハッカソンは終日行うので、別々のチケットになります。両方には参加できませ
ん）
・コントリビューターディ 150枚
・チームハッカソン 50枚
チームハッカソンにはチケットの申し込み時に以下のアンケート項目をつけてください。
得意な分野を選んでください：
・デザイナー
・コーダー
・WordPressエンジニア
それぞれの内容については後日ブログ記事を書く予定になっています。以上、お手数ですがよろしくお願いいたしますー
