### ISSUE TITLE
公式 SNS カバー画像作成

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#41]
公式アカウント用の Twitter と Facebook のカバー画像を作成

担当者: @misha-endo 
## 必要な要素
- WordCamp Tokyo 2016
- 会場名

があれば OK です。わぷーは不要
## サイズ
- Twitter: `1500x500`
- Facebook: `851x350`

**Comment by featherplain** [comment]
@misha-endo 期限は7/15で!

**Comment by misha-endo** [comment]
@featherplain はい！承知いたしました。

**Comment by misha-endo** [comment]
WEB制作班ドライブのsns_coverに格納しました

**Comment by featherplain** [comment]
@misha-endo 
すみません、確認者(Issue を発行した人)が Go サイン出すまでは Issue のクローズはしないでくださいー。判断はこちらでするので、よろしくお願いします:bow:

**Comment by misha-endo** [comment]
@featherplain すいません。閉じちゃいました。了解です。よろしくお願いいたします。

**Comment by featherplain** [comment]
@misha-endo 
画像だけアップロードされても、実際に使った時に大丈夫なのか、どんな見え方になるのかわからないのでなるべく実際の使用感が分かる形で見せてもらいたいです。(最初に言えばよかった...!すみません)

モックアップキット使って試してみたんですが、

Fb は OK
![image](https://cloud.githubusercontent.com/assets/7019355/16833485/8313f49e-49ea-11e6-8e9f-acb9cbcc84f9.png)

Tw は会場名が隠れちゃってるので修正お願いしてもいいですか?
![image](https://cloud.githubusercontent.com/assets/7019355/16833507/98afc2e2-49ea-11e6-9348-ee91a3c5d10f.png)

PC ビューで問題なければひとまず OK なので、モバイルは無視でいいです。そこまでやるのは面倒くさいですし...
Google Drive にモックアップキットあげたのでこちらを使ってください。まあでもこのキットも今の Tw と Fb の画面に沿ってるのか正直分からないんですが、使わないよりはいいかと(^^;;)

**Comment by featherplain** [comment]
キットの場所は `sns_cover/mockup` にあります

**Comment by misha-endo** [comment]
@featherplain モックありがとうございます。作りなおしてみました。うまく入るかわかんなかったんで念のため3パターン用意してみました。うまく見えるものを使ってもらえばと思います。

**Comment by featherplain** [comment]
@misha-endo モックアップにご自身でセットして試して、一番使えそうなもの1種類だけ選んでもらっていいですか?

**Comment by featherplain** [comment]
@misha-endo 一番使えそうなものだけモックアップに入れた状態でキャプチャとって見せてください。

**Comment by misha-endo** [comment]
@featherplain モックいれました。横幅固定PSD通りにはいかないと思うのですが、一番無難そうな上下のテクスチャなしで一旦いれてもらって調整必要であればということではむずかしそうでしょうか？

![2016-07-14 9 59 47](https://cloud.githubusercontent.com/assets/12777029/16840399/82e5d210-4a0f-11e6-9d52-b9d943731035.png)

**Comment by featherplain** [comment]
@misha-endo ありがとうございます! これで OK です。G ドライブ内の不要な画像は削除しておいてください。

**Comment by misha-endo** [comment]
@featherplain よかったです。ありがとうございます！削除してあります。よろしくお願いいたします。

**Comment by featherplain** [comment]
@misha-endo 会場名の変更よろしくお願いします!
https://github.com/wct2016/sns-cover-official
