### ISSUE TITLE
FAQ を作りたい

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#54]
これは余裕があれば
https://github.com/wct2016/wct2016/wiki/questions に書く

**Comment by featherplain** [comment]
## よくある質問

このコメントにどんどん追加する!!

### 参加登録で本名を登録したくない
ニックネームなど好きな名前で OK

**Comment by naokomc** [comment]
こちらお手伝いしましょうか？一般的な FAQ になりますか？（Wifi はありますか？など）

**Comment by featherplain** [comment]
@naokomc ありがとうございます! もし可能であればお願いしたいです。
- 参加登録(チケット関係)
- Wifi
- その他一般的な FAQ 的な内容

参加登録関係は去年いろいろ質問をいただいたので、Web 制作班の方でリストアップしてみようと思います!

ある程度数が集まったら公開できればと。とりあえず FAQ ページだけ作って下書き保存しました。
その他の内容は、何か思いつくものがあれば随時追加して更新という形でどうでしょうか。手が空いてる方ならどなたでも!

@misha-endo ...というわけで、FAQ を作りたいのですがこちら進めてもいいでしょうか。

**Comment by naokomc** [comment]
https://github.com/wct2016/wct2016/wiki/questions

少し更新してみました。本サイトの「よくある質問」ページにもコピペしています。

**Comment by featherplain** [comment]
@naokomc 
ありがとうございます。チケットや参加登録に関して、昨年問い合わせのあったものを追記しました。

**Comment by naokomc** [comment]
@featherplain 
- 参加できなかった場合のTシャツの送付についても追加しました。
- 「参加者一覧ページに名前や写真自体を表示したくない」について、少しだけ書き換えました。

こちら公開しましたー。https://2016.tokyo.wordcamp.org/faq/
「WordCamp とは ?」と「コミュニティガイドライン」の間にメニューとして加えました。
