### ISSUE TITLE
本サイトに関するフィードバック

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#62]
リーダーズからのフィードバックをこちらにコメントする

サイト公開後順次対応予定のもの
- 配布バナー
- 配布用 Facebook カバー
- スポンサーロゴ掲載

**Comment by naokomc** [comment]
## トップ画像

<img width="634" alt="___wordcamp_tokyo_2016" src="https://cloud.githubusercontent.com/assets/34067/16899459/aaccd30a-4c3f-11e6-8f66-537c92b3f492.png">

会場名は、常に「ベルサール新宿グランド コンファレンスセンター」（または「ベルサール新宿グランド 5F コンファレンスセンター」）に統一したほうが混乱を招かないのでベターかと。

## チケット設定

本サイトのほうで、以下の変更を加えました。
- イベント名を「WordCamp Tokyo」から「WordCamp Tokyo 2016」に変更。
- 返金機能を有効化し、9/10までに設定。
  ( メールテンプレートを（翻訳されている）2015年版からコピペ。キャンセルについては「※ チケットのキャンセルは2016年8月17日までに上記の URL からお願い致します。Tシャツが含まれないチケットのみ、9月10日までキャンセル可能です。」としました。

↑ もし意図的にされていなかった場合は、戻してくださいませ。

## 参加登録ページ
- 「お子様連れの方へ」は、全員が必要な情報ではないので最後でもいいと思います。
- ハッカソン、コントリビューターデイについては後日詳細を発表しますと冒頭に書いておくといいかもしれません。例「 Day 1 はセッションのみ、Day 2 はチーム制のハッカソンとコントリビューターデイを行います。詳細については後日発表します。」

**Comment by featherplain** [comment]
@naokomc 

> トップ画像

会場名直しておきます!

> チケット設定

ありがとうございます! 設定し忘れていたので助かりました。

> 参加登録ページ

もろもろ了解しました!

**Comment by YoshinoriKobayashi** [comment]
チケットの並び順を変えてあげたほうがよいかも。
会の進行順にしたほうがよいと思います。（1日目チケットー＞2日目チケット）

次のような感じかな？

[ 一般参加 ] WordCamp Tokyo 2016 Day 1
[ Micro Sponsor ] WordCamp Tokyo 2016 Day 1
[ Tシャツ付き一般参加 ] WordCamp Tokyo 2016 Day 1

[ Contributor Day ] WordCamp Tokyo 2016 Day 2
[ Hackathons ] WordCamp Tokyo 2016 Day 2

<img width="1094" alt="___wordcamp_tokyo_2016" src="https://cloud.githubusercontent.com/assets/5963990/16909328/079b404e-4d0d-11e6-9949-3e8637b74a32.png">

**Comment by featherplain** [comment]
@YoshinoriKobayashi 
ありがとうございます!

残念ながらチケットの表示順の設定はできません。。。

https://2016.tokyo.wordcamp.org/tickets/
本番サイトでは恐らくチケット作成順か、開催順で表示されるみたいです。

**Comment by mekemoke** [comment]
コスギ＠更新班です。
昨年同様、重要なリンクはボタンぽいスタイルがあるとうれしいです。
https://2015.tokyo.wordcamp.org/join_info/
class="btnFull" で適用されるとうれしいです！

**Comment by mekemoke** [comment]
SNSでシェアする際、デフォルトのサムネイル画像があるとウレシイです。
Facebookは1200x630が最適サイズで、Twitterが２：１だったと思うので、
FBに合わせても良いかもしれません。

**Comment by naokomc** [comment]
@YoshinoriKobayashi 
チケットの表示順、公開日時の変更で対応が可能だったので変えてみました（日付ごとに値段が安い順に並べて、その下に18才未満のを並べました）。ご確認ください。

https://wordpress.org/support/topic/change-order-of-tickets-listed-on-my-page

**Comment by naokomc** [comment]
リンクの色、特に :visited は見分けが付きづらく感じます。もう少しわかりやすくしていただけると嬉しいです 😃 
ポツポツとすいません… 🙇  

![link-sample](https://cloud.githubusercontent.com/assets/34067/16940094/42a547c4-4dc2-11e6-9d4a-74cc89ab66de.png)

**Comment by featherplain** [comment]
@naokomc 
ありがとうございます! #37 で対応します!

@mekemoke ありがとうございます! #69 と #70 で対応します!

**Comment by YoshinoriKobayashi** [comment]
@naokomc  @featherplain   表示順の対応、ありがとうございます！

**Comment by featherplain** [comment]
@naokomc 

https://github.com/wct2016/wct2016/issues/62#issuecomment-233540479
リンクの色を変更しました!

![image](https://cloud.githubusercontent.com/assets/7019355/16985223/11c361e2-4eba-11e6-9cef-e04bec134941.png)

**Comment by featherplain** [comment]
@mekemoke 
https://github.com/wct2016/wct2016/issues/62#issuecomment-233525552 に関して

ボタンスタイルを作りました!
昨年とは違う class になりますので、非公開ページのスタイルガイドを作成しました。ご確認ください。今年は何となく角丸ボタンにしてみました^^
https://2016.tokyo.wordcamp.org/styleguide/

**Comment by mekemoke** [comment]
@featherplain
早速使わせていただきました！ありがとうございました！

**Comment by featherplain** [comment]
とりあえずクローズ。あとは個別に Issue で
