### ISSUE TITLE
WordPress の設定

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#7]
@misha-endo 
# 概要

依頼者: @featherlplain
期限: 2/29
想定作業日数: 1日
## 作業後のチェック

タスクリストが全部消化できたら、班長判断でクローズしてもらって構いません。

他の課題も、作業が完了したら確認者(大抵の場合遠藤さんだと思います)にアサインを渡す形にすると運用しやすいかと思います。
# タスクリスト一覧

WordPress の初期設定です。下記の設定をお願いします。
## ブログ用固定ページの作成
- 固定ページタイトルを `お知らせ`
- 内容は空
- そのまま公開、もしくは誰かがが最初に記事を書くタイミングで公開
## カテゴリー
- [x] `Uncategorized` のカテゴリ名を `お知らせ`　に変える

WordPress の初期状態では、`Uncategorized` のカテゴリーがあります。このカテゴリは削除できないので、カテゴリの名前を編集してください。
### メニュー
- [x] `create new menu` でメニューを作成
- [x] 公開済みのページをメニューに追加
  - 開催概要
  - スポンサー募集
  - お知らせ
  - WordCamp とは?
### ウィジェット
- [ ] Twitter のタイムラインウィジェット
- [ ] Facebook の Likebox ウィジェット

去年のを参考にしてくださいー
### 投稿
- [x] Hello World!
- [x] Welcome to WordCamp Tokyo
### Jetpack
- [x] Jetpack の Photon を有効化
- [x] Tiled Galleries を有効化

去年は設定してなかったんですが、Photon の設定しちゃいましょう。
https://jetpack.me/support/photon/
### 一般設定
- [x] `キャッチフレーズ`: キャッチフレーズが `Just Another WordPress Site` になっているので、去年や一昨年を参考に変えてください。
### 表示設定
- [x] `フロントページの表示` : 固定ページ
  - [x] `フロントページ`: 開催概要
  - [x] `投稿ページ`: お知らせ
### ディスカッション
- [x] デフォルトのままだとコメントができるようになっているので、コメントができないようにしてください。ピンバックは OK です。
### パーマリンク設定
- [x] `Post name` にする

絶対これ! というものはないんですが、post name にしておくのが無難かなーと思います。判断はお任せします。
### Sharing
- [ ] Twitter
- [ ] Facebook
- [x] `Sharing Label` は任意の文言で OK 
- [x] `Show buttons on` : 去年を参考にチェックを入れてください。
- [x] `Twitter Site Tag`: これも去年のを参考に

**Comment by featherplain** [comment]
@misha-endo 

issue を発行する時は
- issue の期限を記載する
- 確認者へアサインを渡すように伝える
- 想定作業日数は、目安です。
- ひとつの課題に対して複数やることがあったり、確認者がチェックする項目が複数ある場合は、上記のようにチェックボックスとリストを活用するといかなと!

**Comment by misha-endo** [comment]
上記、ありがとうございます。

確認いたしました
とくに、

＞issue の期限を記載する。
＞チェックボックスとリストを活用する

いいですね。
とっても管理しやすくなりそうです。

**Comment by misha-endo** [comment]
@featherplain 
Sharingのリンク設定方法について聞かせて下さい〜

**Comment by featherplain** [comment]
@misha-endo 

リンクの設定は必要ありません。Drag and drop するだけで OK です。
シェア用のリンクは Jepack 側で設定されています。

パブリサイズ共有がオンになっていたのでこちらでオフにしておきました。
