### ISSUE TITLE
参加登録画面の登録ボタンの修正

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#71]
> 参加登録画面（ https://2016.tokyo.wordcamp.org/tickets/ ）の登録ボタンが下の要素のせい（マイナスマージンのせい）で押せる範囲が少ないです。
> IE、Chrome なら上から2/3程度が押せる領域ですが、Firefoxだと上から1/4程度しか押せる領域がありません。

**Comment by featherplain** [comment]
@naokomc 

ボタンが押しにくい問題修正しました!

## 検証端末
- Windows 10 実機: Edge, IE11, Firefox, Chrome
- Mac: Chrome, Safari, Firefox
- Mobile: iPhone 5s 実機

上記で検証済み、全部動作確認しました。
ブラウザは最新版のみ、IE は10以下は切り捨て、Android もクリティカルなものでない限り検証・対応はしない方針でいきます:bow: (大変なので...すみません><)

**Comment by Kenshino** [comment]
やった！
