### ISSUE TITLE
スポンサーロゴ掲載&ページについて

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#77]
関連: #29
## スポンサーページ

URL: `https://2016.tokyo.wordcamp.org/sponsors/{sponsor_slug}`

スポンサーからあがってきた紹介文の原稿をもとにマークアップしてください。見出し ( `h2`, `h3` ) と本文 ( `p` ) 程度で十分だと思います。
### サンプルページ

https://2016.tokyo.wordcamp.org/sponsor/sample/ (非公開なのでログインしてください)

参考: 
- https://2015.tokyo.wordcamp.org/sponsor/kusanagi/ (Gold)
- https://2015.tokyo.wordcamp.org/sponsor/firstserver/ (Silver)
### 掲載方法

WordCamp が用意する **スポンサーウィジェット** を使ってサイトのフッターにスポンサーロゴを表示
( [ 外観 ] -> [ ウィジェット ] から設定 )
### ロゴ掲載に必要な作業
- スポンサーページにてスポンサーランクの入力: スポンサー班
- スポンサーページにてロゴ(アイキャッチ画像)の設定: スポンサー班
- ウィジェットの有効化: Web 班
### スポンサーウィジェット

![ss_sponsor_widget](https://cloud.githubusercontent.com/assets/7019355/17296744/a4c0f78e-583d-11e6-8aaa-484077ac401a.png)

WCTokyo 2016 ではフッター部分にスポンサーロゴを表示させたいので、フッターウィジェットエリアにスポンサーウィジェットを設置して、有効化します。

![ss_sponsor_logo](https://cloud.githubusercontent.com/assets/7019355/17296880/37f34304-583e-11e6-8d6f-97b1e50792e9.png)

有効化すると、スポンサーページで設定したロゴ(アイキャッチ画像)とスポンサーランクがウィジェットに紐付けられてフッターに表示されます。スポンサーランク毎に分類されますので、ランクの設定を忘れずにお願いします。

**スポンサーウィジェットを有効化後はスポンサー情報を公開した時点で、フッターにロゴとリンクが自動反映**されます。画像のリンク先は自動的にスポンサーページの URL となります。
### サイズ

`1200x630`: Facebook でシェアする際の OGP 画像の推奨サイズが `1200x630` のため
### 形式
- png
- 背景色を透過ではなく**白**にする
### 配置

Ai のアートボードに天地中央に配置する
ロゴ画像作成用 Ai : https://www.dropbox.com/s/0kcnvmasu63zpic/logo_sample.ai?dl=0
## その他

スポンサーページでスポンサー情報を作成する際、スラッグはなるべく英語表記にしたほうがいいかと思います。

**Comment by featherplain** [comment]
@misha-endo 
詳細をまとめたんですが、こんな感じでどうでしょうか。何かあればコメントください。
とりあえず、スポンサー班の吉川さんと相談して初回ロゴ掲載に向けて期限を決めましょう。

**Comment by naokomc** [comment]
もう一手間で申し訳ないのですが、お手すきの時でかまいませんので[マイクロスポンサー一覧ページ](https://2016.tokyo.wordcamp.org/sponsors/micro-sponsors/)へのリンクをフッターにも入れていただけますか？ブロンズの下に、さり気なくテキストリンクで構いません。

**Comment by featherplain** [comment]
@naokomc 

![image](https://cloud.githubusercontent.com/assets/7019355/17544559/0ae3d726-5f13-11e6-9cef-a9e28ac64b48.png)

遅くなってすみません。対応しました。

**Comment by naokomc** [comment]
@featherplain どうもありがとうございました！！！

そして何度も申し訳ないのですが、こちらもいつでも良いので追加希望です。金銭ではなくサービスを提供してくださった、スポンサーさんです。
Micro と横並びでもかまいませんし、ロゴも小さめで OK です。

## スポンサーレベル名: In-kind

### In-kind スポンサー1: Backlog
- スポンサー名: Backlog
- ロゴファイル: https://nulab-inc.com/download/backlog/png/combination.png
- リンク先: https://2016.tokyo.wordcamp.org/sponsor/backlog/

### In-kind スポンサー2: StickerGiant
- スポンサー名: Backlog
- ロゴファイル: http://sg-static-cdn.sgsr.us/data/Stickergiant-Logo-300px__55831014402e5.png?v65
- リンク先: https://2016.tokyo.wordcamp.org/sponsor/stickergiant/

今のところこれ以外に追加の予定はありません。
スポンサー投稿タイプ用にスポンサーレベル「In-kind」は作っていませんが、必要でしたら作ります or 作ってくださいませ。

よろしくお願いします。

**Comment by featherplain** [comment]
@naokomc 対応しました!
