### ISSUE TITLE
English->Ticketsで英語ページが表示されない？？

### ISSUE THREAD

**Issue by YoshinoriKobayashi** [wct2016/wct2016#78]
グローバルメニューから、English->Tickets　で辿っても、参加登録が日本語のままになります。
英語表記での参加登録ページが表示されると認識していました。既に既知ならごめんなさい^^;

**Comment by waviaei** [comment]
参加登録の固定ページは英語版を作れない（＊）ので、仕方なく英語のメニューからも日本語の「参加登録」にリンクしています。英語はTicket Details（チケットの詳細）というメニューアイテムがあり、そこに詳細を書いてあります。Ticket Detailsをまず確認してもらって、「参加登録」にいってもらう感じです。

Ticket Details→参加登録との導線と、「参加登録」に英語の説明が必要ですね。追加しないと…

＊固定ページ自体は作れますが、フォームが完全に英語にはできないので、作っても中途半端で逆にわかりづらくなる感じです。

**Comment by naokomc** [comment]
> Ticket Details→参加登録との導線と、「参加登録」に英語の説明

上記対応済みなのでとりあえずクローズします。

https://2016.tokyo.wordcamp.org/en/ticket-details/ (上部にボタンつけました)

認識済みということでもし改善案があれば手を加えてください。
