### ISSUE TITLE
SNS のシルエット画像の作成

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#8]
期限:
- [ ] Twitter のシルエットアイコン画像
- [ ] Facebook のシルエットアイコン画像

サイズは Google スプレッドシートの [ 画像 ] シートを参照してください。
昨年のものを `2016` に変えるだけでいいと思います。データは Google ドライブの `2015/design/silhouette` にあります。

@misha-endo : アサイン者と期限の設定お願いします! 現時点では遠藤さんにアサイン振ってあります。

**Comment by misha-endo** [comment]
了解いたしました。
@momonotsubo 
こちら来週水曜日くらいまでに壺井さんおねがいできますか？

**Comment by momonotsubo** [comment]
はい！大丈夫です！
わぷーの去年の画像とかは、Googleドライブに入っているのでしょうか？

**Comment by featherplain** [comment]
@momonotsubo 

こちらですー!

> サイズは Google スプレッドシートの [ 画像 ] シートを参照してください。
> 昨年のものを 2016 に変えるだけでいいと思います。データは Google ドライブの
> `2015/design/silhouette` にあります。

**Comment by momonotsubo** [comment]
@fatherplain 了解です！ありがとうございます！

**Comment by momonotsubo** [comment]
@misha-endo 　 Twitter のシルエットアイコン画像
 Facebook のシルエットアイコン画像作成して、Googleドライブの中に入れています！

**Comment by misha-endo** [comment]
@momonotsubo 返信遅くなりすいません。ありがとうございます！確認させていただきます〜〜
