### ISSUE TITLE
.alignright が float:left になってる

### ISSUE THREAD

**Issue by waviaei** [wct2016/wct2016#80]
`.alignright {
    display: inline;
    float: left;
    margin-right: .9375rem;
    margin-bottom: .9375rem;
}`

**Comment by featherplain** [comment]
@waviaei 

ご報告ありがとうございます! 修正して本番サイトに反映しました。

![image](https://cloud.githubusercontent.com/assets/7019355/17172969/fa4b0f14-5432-11e6-92d9-a652828e0032.png)
