### ISSUE TITLE
問い合わせフォームの設置

### ISSUE THREAD

**Issue by featherplain** [wct2016/wct2016#9]
@misha-endo 
- [ ] 委員長に、開催概要ページ作成にフォーム設置も含まれているのか一応確認
## フォーム作成作業

担当者: @misha-endo 
- [ ] リーダーズで共有している Google ドライブのフォルダ内に、問い合わせ用の Google フォームを作成
- [ ] フォームの内容を飛ばす、回答用のスプレッドシートを作成 (キャプチャ参照)
- [ ] 通知設定: 問い合わせ対応の担当者の Gmail アドレスを、回答用のスプレッドシートの `ツール` -> `通知ルール` から設定(キャプチャ参照)

![image](https://cloud.githubusercontent.com/assets/7019355/13394827/3fae5ff4-df2e-11e5-8b58-dd01da3c141d.png)

![image](https://cloud.githubusercontent.com/assets/7019355/13394804/1c802440-df2e-11e5-93fd-fc155a9e0bfd.png)
## 開催概要へのフォーム設定作業

担当者: **遠藤さんのフォーム作成が終わったらアサインを誰かに渡すのか、遠藤さんが引き続き作業するのかの判断をお願いします。**

下記の内容を開催概要に追記してください。

``` html
<dt>お問い合わせ</dt>
<dd>イベントに関してお問い合わせがある方は、<a href="https://twitter.com/wctokyo" target="_blank">Twitter</a>、<a href="http://www.facebook.com/wordcamptokyo" target="_blank">Facebook</a> の WordCamp Tokyo 2016公式アカウント宛にご連絡ください。<br> 
<small>※ 恐れ入りますが、イベント概要に関しては現時点で公開されている事以外はお答えすることができません。</small>
<small>※ 返信までに3、4日かかる場合がございます。万一返信がない場合、お手数ですが再度お問い合わせいただきますようお願い致します。</small>
</dd>
<dd><a class="btn" href="Google フォームのリンク" target="_blank">お問い合わせフォーム</a></dd>
```

**Comment by featherplain** [comment]
@misha-endo 
直子さんがショートコードで問い合わせページ作ってくれてたのでクローズします!

**Comment by misha-endo** [comment]
![寿司ゆき:ok](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/03.png)

**Comment by featherplain** [comment]
問い合わせページで修正お願いしたい箇所があるため再オープンします!

**Comment by misha-endo** [comment]
了解です。

**Comment by misha-endo** [comment]
追記文いれていないですね。

**Comment by featherplain** [comment]
@misha-endo 

以下の点修正と追加をお願いします!

> ※ チケットの増枠に関するお問い合わせはご遠慮ください
- [x] これは2015の参加登録受付終了後にチケット増枠に関する問い合わせが増えたため追加した文言です。なので削除をおねがいします!
- [x] 問い合わせが来てからすぐに返信できるとは限らないため、`※ 返信までに3、4日かかる場合がございます。万一返信がない場合、お手数ですが再度お問い合わせ頂ますようお願い致します。` の一文を追加をお願いします。

**Comment by misha-endo** [comment]
@featherplain 
修正しました

**Comment by misha-endo** [comment]
@featherplain 念のため下記も入れました。
※ 恐れ入りますが、イベント概要に関しては現時点で公開されている事以外はお答えすることができません。

**Comment by misha-endo** [comment]
@featherplain ![寿司ゆき:yes](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/01.png)
