### ISSUE TITLE
profile.worodpress.org へのリンクが欲しい。

### ISSUE THREAD

**Issue by torounit** [wct2016/wct2016#90]
スピーカー紹介のページから、profile.worodpress.org へのリンクが自動で付けば良いなと思いますがどうでしょう。

かなり無理臭いですかね・・・・・

**Comment by torounit** [comment]
ローカルでの検証時には、wc-post-types 等を有効にした上で、

```
add_filter( 'wcpt_speaker_post_avatar_min_site_id', '__return_zero');
```

を実行する必要があります。

**Comment by featherplain** [comment]
@torounit 
WordCamp サイトでは、NO JS, NO PHP でテーマファイルは一切触れないため対応は難しそうです...(>人<;) .org アカウントを表示させるような記載もマニュアルに書かれてないっぽいです。

参考: 
WordCamp サイトを作る上でのもろもろが書かれているマニュアル:
https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/web-presence/
